In [1]:
import pyarrow.dataset as ds
import pandas as pd
from pathlib import Path
import numpy as np
import statsmodels.api as sm
import os
from tqdm import tqdm
import scipy

In [2]:
ROOT = Path("/home/hanwenying")
DATA = ROOT / "rothman-data/gltd"
OUT  = ROOT / "rothman-anna/gltd/out"
BETA = OUT / "betas"
RESID = OUT / "resid"

# FOR EACH TISSUE

In [8]:
tissue = "Brain - Hippocampus"
tissue_betas = pd.read_csv(BETA / f"{tissue}.tsv", sep='\t')

In [9]:
tissue_betas

                     GENE  LOGLENGTH      BETA         T         P
0       ENSG00000310526.1   3.830909 -0.008557 -0.378866  0.705108
1       ENSG00000308579.1   2.901458  0.195920  3.389062  0.000814
2       ENSG00000269981.1   2.453318  0.157881  3.048436  0.002546
3       ENSG00000310527.1   3.880928  0.036939  1.377597  0.169555
4       ENSG00000225880.7   4.373390  0.011334  0.810774  0.418263
...                   ...        ...       ...       ...       ...
21884  ENSG00000131002.15   3.197005  0.007280  0.379069  0.704957
21885   ENSG00000267793.1   2.755875  0.000978  0.058376  0.953496
21886   ENSG00000260197.1   3.425860  0.012026  0.493600  0.622020
21887  ENSG00000012817.16   3.976029 -0.002038 -0.052864  0.957882
21888  ENSG00000198692.10   3.604550 -0.045291 -1.465542  0.144025

[21889 rows x 5 columns]

In [10]:
m, b, _, _, _ = scipy.stats.linregress(tissue_betas['LOGLENGTH'], tissue_betas['BETA'])

In [11]:
ypred = m * tissue_betas['LOGLENGTH'] + b
resid = tissue_betas['BETA'] - ypred

In [12]:
rho_betas, _ = scipy.stats.spearmanr(tissue_betas['LOGLENGTH'], tissue_betas['BETA'])
rho_resid, _ = scipy.stats.spearmanr(tissue_betas['LOGLENGTH'], resid)

print(rho_betas, rho_resid)

-0.1506702839546978 0.030722710604763285

In [ ]:
tissue_betas['RESIDUAL'] = resid
tissue_betas.to_csv(RESID / f"{tissue}.tsv", sep='\t', index=False)

                     GENE  LENGTH      BETA         T         P  RESIDUAL
0       ENSG00000310526.1     NaN  0.104192  3.406535  0.000823  0.048340
1       ENSG00000308579.1     NaN  0.111108  1.546438  0.123881  0.155482
2       ENSG00000268903.1     NaN  0.068285  1.449519  0.149057  0.164175
3       ENSG00000269981.1     NaN  0.088005  1.187745  0.236610  0.073820
4       ENSG00000310527.1     NaN  0.124096  3.697683  0.000294  0.026005
...                   ...     ...       ...       ...       ...       ...
26856  ENSG00000182484.15     NaN  0.091180  2.504857  0.013203       NaN
26857   ENSG00000235001.3     NaN -0.028997 -1.594746  0.112649       NaN
26858   ENSG00000235649.2     NaN -0.003260 -0.134779  0.892948       NaN
26859   ENSG00000215414.4     NaN  0.012309  0.609605  0.542947       NaN
26860   ENSG00000185275.6     NaN -0.094140 -2.173555  0.031138       NaN

[26861 rows x 6 columns]